;;; whisper-languages.el -*- lexical-binding: t; -*-

(defvar whisper--languages
  '(("Auto-Detect" . "auto")
    ("English" . "en")
    ("Chinese" . "zh")
    ("German" . "de")
    ("Spanish" . "es")
    ("Russian" . "ru")
    ("Korean" . "ko")
    ("French" . "fr")
    ("Japanese" . "ja")
    ("Portuguese" . "pt")
    ("Turkish" . "tr")
    ("Polish" . "pl")
    ("Catalan" . "ca")
    ("Dutch" . "nl")
    ("Arabic" . "ar")
    ("Swedish" . "sv")
    ("Italian" . "it")
    ("Indonesian" . "id")
    ("Hindi" . "hi")
    ("Finnish" . "fi")
    ("Vietnamese" . "vi")
    ("Hebrew" . "he")
    ("Ukrainian" . "uk")
    ("Greek" . "el")
    ("Malay" . "ms")
    ("Czech" . "cs")
    ("Romanian" . "ro")
    ("Danish" . "da")
    ("Hungarian" . "hu")
    ("Tamil" . "ta")
    ("Norwegian" . "no")
    ("Thai" . "th")
    ("Urdu" . "ur")
    ("Croatian" . "hr")
    ("Bulgarian" . "bg")
    ("Lithuanian" . "lt")
    ("Latin" . "la")
    ("Maori" . "mi")
    ("Malayalam" . "ml")
    ("Welsh" . "cy")
    ("Slovak" . "sk")
    ("Telugu" . "te")
    ("Persian" . "fa")
    ("Latvian" . "lv")
    ("Bengali" . "bn")
    ("Serbian" . "sr")
    ("Azerbaijani" . "az")
    ("Slovenian" . "sl")
    ("Kannada" . "kn")
    ("Estonian" . "et")
    ("Macedonian" . "mk")
    ("Breton" . "br")
    ("Basque" . "eu")
    ("Icelandic" . "is")
    ("Armenian" . "hy")
    ("Nepali" . "ne")
    ("Mongolian" . "mn")
    ("Bosnian" . "bs")
    ("Kazakh" . "kk")
    ("Albanian" . "sq")
    ("Swahili" . "sw")
    ("Galician" . "gl")
    ("Marathi" . "mr")
    ("Punjabi" . "pa")
    ("Sinhala" . "si")
    ("Khmer" . "km")
    ("Shona" . "sn")
    ("Yoruba" . "yo")
    ("Somali" . "so")
    ("Afrikaans" . "af")
    ("Occitan" . "oc")
    ("Georgian" . "ka")
    ("Belarusian" . "be")
    ("Tajik" . "tg")
    ("Sindhi" . "sd")
    ("Gujarati" . "gu")
    ("Amharic" . "am")
    ("Yiddish" . "yi")
    ("Lao" . "lo")
    ("Uzbek" . "uz")
    ("Faroese" . "fo")
    ("Haitian creole" . "ht")
    ("Pashto" . "ps")
    ("Turkmen" . "tk")
    ("Nynorsk" . "nn")
    ("Maltese" . "mt")
    ("Sanskrit" . "sa")
    ("Luxembourgish" . "lb")
    ("Myanmar" . "my")
    ("Tibetan" . "bo")
    ("Tagalog" . "tl")
    ("Malagasy" . "mg")
    ("Assamese" . "as")
    ("Tatar" . "tt")
    ("Hawaiian" . "haw")
    ("Lingala" . "ln")
    ("Hausa" . "ha")
    ("Bashkir" . "ba")
    ("Javanese" . "jw")
    ("Sundanese" . "su")
    ("Cantonese" . "yue")
  )
  "Alist of whisper supported languages for audio.

The language codes are from:
https://github.com/ggerganov/whisper.cpp/blob/f7502dca872866a310fe69d30b163fa87d256319/src/whisper.cpp#L314")

(provide 'whisper-languages)
